# Generated by Django 3.1.4 on 2020-12-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
