# Generated by Django 3.1.4 on 2020-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upvotes',
            field=models.TextField(default='{"upvoters": []}'),
        ),
    ]
