# Generated by Django 3.1.4 on 2020-12-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
